### ISSUE TITLE
amazons3 config file is missing

### ISSUE THREAD

**Issue by ghost** [volodymyr-mk/SailsJSProject#1]
Hey,

I noticed config/amazons3.js is missing. It's required in api/services/AmazonS3Service.js

Thanks for this nice work. I'm a new programmer and it's very inspiring ^^

Vendreur Jack

**Comment by volodymyr-mk** [comment]
Hi @VendreurJack ,

This config is private and under gitignore cause it have private amazon s3 credentials.

**Comment by ghost** [comment]
Ok thanks !

Can you add a model of this file (without your credentials infos), please ? ^^

**Comment by ghost** [comment]
I already create one but I have a problem with the region : when I give it, for example, "us-west-2" I have an issue ...

**Comment by volodymyr-mk** [comment]
module.exports = {
    accessKeyId: '',
    secretAccessKey: '',
    region: 'EU_WEST_1',
    BucketName: '',
    ObjectName: 'testProject/' //for e.g.
};

I did not use official aws nodejs module, so I need to pass some constant, you can find it in node_modules folder

**Comment by ghost** [comment]
Ok that's great, thanks ;)
